explicitly require ActiveRecord::Base
Otherwise it is possible to get exception when running tests: `test/test_helper.rb:23:in `<class:TestCase>': undefined method `fixtures' for ActiveSupport::TestCase:Class (NoMethodError)`

This adapter uses ActiveRecord::Base so it is only fair to require it.